### ISSUE TITLE
Namespace errors

### ISSUE THREAD

**Issue by weberBen** [dddxiu/php-logic-simplifier#1]
I found few import errors when using the package :

- In `Exception\InvalidOperatorException.php`, `Exception\VariableNotFoundException.php`: change namespace `namespace Logic\Simplifier` to `namespace Logic\Simplifier\Exception;`
- In `SimplificationTable.php`: missing `use Logic\Simplifier\parser;`
- In `ReducedPermutation.php`: change `use Logic\Simplifier\Exception;` to `use Logic\Simplifier\Exception\ValueError;`
- In `Expression\Operator.php`, `Expression\Variable.php`: add `use Logic\Simplifier\Exception\VariableNotFoundException;`

**Comment by dddxiu** [comment]
you can post me the expression

**Comment by weberBen** [comment]
It's not a particular expression that causes all the errors : I'm using the package for a module inside a framework (Prestashop which uses Synfony) which apparently have a problem with imports inside theses files (and it's works fine with other php package for that framework).
For example without any modification to the package, when I do `Logic\Simplifier\SimplificationTable::simplify("a | (a & b)")` I got an `ClassNotFoundException` for `parser` in `simplify` function (from Synfony)

**Comment by dddxiu** [comment]
I fix namespace error，composer need time  to update

**Comment by weberBen** [comment]
Great !
And thanks for that package
